/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domino2;

/**
 *
 * @author demer
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    
    private int game = 0;
    private Solo1Frame solo1;
    private HungarianFrame hung;
    private CardinalFrame cardinal;
    
    public Help() {
        initComponents();
    }
    
    public Help(int game) {
        initComponents();
        this.game = game;
        
        if (game == 1){
            jLabel1.setText("Tips and informations about Solo 1");
            textArea1.setText("dialegeis ena domino apo ta de3ia pros ta aristera apo opoia seira 8eleis. \n" + "To paixnidi teleiwnei otan teleiwsoun ola ta domino h den ginete allo domino na paixtei");
        }
        else if (game == 2){
            jLabel1.setText("Tips and informations about Hungarian");
            textArea1.setText("The lead player sets down the first tile and then continues to play tiles onto \n" + "the open played end of the domino layout with same-number adjacent to same-number (doubles placed horizontally onto ends not allowing play to branch four ways).\n" + " Once the lead player is unable to play a tile onto the open end of the layout, play passes to the next player in turn \n" + "who then plays all their playable tiles onto the end of the layout until no more plays can be made.\n" +  "Play continues like this with each player in turn playing as many of their tiles as they can in their turn.\n" +
                                "\n" +
                                "Once a player has dominoed by setting their last tile, or the game is blocked \n" +"with no player able to set a tile, the round is over and the player who dominoed or has the lowest total of pips left in their hand, is the winner of that round.\n" + "Players score the total number of pips left in their remaining hand of dominoes.\n" +
                                "\n" +
                                "A number of rounds are played and the first player to score a set total \n" + "(say 100, 150, 200 or 250 points), loses the game.  Play may continue with the loser being eliminated from the game and with the remaining players playing as before\n" +"until only one is left, the winner.\n");
        }
        else{
            jLabel1.setText("Tips and informations about Cardinal");
            textArea1.setText("The tiles must be placed so that the two of" +
            "their sides touching, have a sum of 7 e.g. if one side of the tile is 5, then it\n" +
            "a tile next to it should have the number 2 on one side. Double\n" +
            "white and all tiles whose total points are the number 7 e.g. 3/4, 1/6 is like\n" +
            "Cardinals and can always be placed. Although a player can\n" +
            "play, can also get a tile from the stack. On the contrary, if a player can not\n" +
            "to play, he takes one-tile from the stack until he can. However, 2 tiles must be\n" +
            "they always stay in the stack. The round ends when a player places all his tiles\n" +
            "or when no player can place tiles. The player who has the least\n" +
            "points earns the round. Takes as points all the points of his opponents and from\n" +
            "removing them from these points. A lot ends when a player exceeds 100 points.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tips");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
