/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domino2;

import java.util.ArrayList;

/**
 *
 * @author demer
 */
public class Solo1Frame extends javax.swing.JFrame {

    private Table table;
    private Pack pack;
    private int b= 0;
    private Solo1 solo;
    
    /**
     * Creates new form Solo1Frame
     */
    public Solo1Frame() {
        initComponents();
    }
    
    public Solo1Frame(String name) {
        initComponents();
        pack = new Pack(6);
        table = new Table();
        solo = new Solo1(pack,table);
        jLabel1.setText("Hello " + name + "! Welcome to the Solo 1 Domino Game!");
        createNshuffleTiles();
        b7.setEnabled(true);
        b14.setEnabled(true);
        b21.setEnabled(true);
        b28.setEnabled(true);       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textArea2 = new java.awt.TextArea();
        b1 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        jScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("Player");

        jButton1.setText("Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textArea2.setBackground(new java.awt.Color(0, 204, 204));
        textArea2.setForeground(new java.awt.Color(255, 255, 255));

        b1.setText("jButton2");
        buttonGroup1.add(b1);
        b1.setEnabled(false);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b8.setText("jButton3");
        buttonGroup1.add(b8);
        b8.setEnabled(false);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b15.setText("jButton4");
        buttonGroup1.add(b15);
        b15.setEnabled(false);
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b22.setText("jButton5");
        buttonGroup1.add(b22);
        b22.setEnabled(false);
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        b2.setText("jButton6");
        buttonGroup1.add(b2);
        b2.setEnabled(false);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b9.setText("jButton7");
        buttonGroup1.add(b9);
        b9.setEnabled(false);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b16.setText("jButton8");
        buttonGroup1.add(b16);
        b16.setEnabled(false);
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b23.setText("jButton9");
        buttonGroup1.add(b23);
        b23.setEnabled(false);
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        b3.setText("jButton10");
        buttonGroup1.add(b3);
        b3.setEnabled(false);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b10.setText("jButton11");
        buttonGroup1.add(b10);
        b10.setEnabled(false);
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b17.setText("jButton12");
        buttonGroup1.add(b17);
        b17.setEnabled(false);
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b24.setText("jButton13");
        buttonGroup1.add(b24);
        b24.setEnabled(false);
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });

        b4.setText("jButton14");
        buttonGroup1.add(b4);
        b4.setEnabled(false);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b11.setText("jButton15");
        buttonGroup1.add(b11);
        b11.setEnabled(false);
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b18.setText("jButton16");
        buttonGroup1.add(b18);
        b18.setEnabled(false);
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b25.setText("jButton17");
        buttonGroup1.add(b25);
        b25.setEnabled(false);
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });

        b5.setText("jButton18");
        buttonGroup1.add(b5);
        b5.setEnabled(false);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b12.setText("jButton19");
        buttonGroup1.add(b12);
        b12.setEnabled(false);
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b19.setText("jButton20");
        buttonGroup1.add(b19);
        b19.setEnabled(false);
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b26.setText("jButton21");
        buttonGroup1.add(b26);
        b26.setEnabled(false);
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });

        b6.setText("jButton22");
        buttonGroup1.add(b6);
        b6.setEnabled(false);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b13.setText("jButton23");
        buttonGroup1.add(b13);
        b13.setEnabled(false);
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b20.setText("jButton24");
        buttonGroup1.add(b20);
        b20.setEnabled(false);
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b27.setText("jButton25");
        buttonGroup1.add(b27);
        b27.setEnabled(false);
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });

        b7.setText("jButton2");
        buttonGroup1.add(b7);
        b7.setEnabled(false);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b14.setText("jButton3");
        buttonGroup1.add(b14);
        b14.setEnabled(false);
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b21.setText("jButton4");
        buttonGroup1.add(b21);
        b21.setEnabled(false);
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b28.setText("jButton5");
        buttonGroup1.add(b28);
        b28.setEnabled(false);
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });

        jScore.setText("Keep Going!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textArea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(b22))
                                    .addComponent(b15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScore))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b23))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(b17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b24))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b26))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b27, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b28))
                                .addGap(0, 37, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(3, 3, 3)
                .addComponent(jScore, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6)
                    .addComponent(b7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8)
                    .addComponent(b9)
                    .addComponent(b10)
                    .addComponent(b11)
                    .addComponent(b12)
                    .addComponent(b13)
                    .addComponent(b14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b15)
                    .addComponent(b16)
                    .addComponent(b17)
                    .addComponent(b18)
                    .addComponent(b19)
                    .addComponent(b20)
                    .addComponent(b21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b24)
                        .addComponent(b22)
                        .addComponent(b25)
                        .addComponent(b26)
                        .addComponent(b27)
                        .addComponent(b28))
                    .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(textArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Help help = new Help(1);
        help.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(12);
        printTable();
        solo.removeTile(solo.getList4(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b6.setVisible(false);
    }//GEN-LAST:event_b24ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(18);
        printTable();
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b12.setVisible(false);
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(22);
        printTable();
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b13.setVisible(false);
    }//GEN-LAST:event_b13ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(25);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(1));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
       b7.setVisible(false);
    }//GEN-LAST:event_b7ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(5);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(1));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b2.setVisible(false);
    }//GEN-LAST:event_b2ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(8);
        printTable();
        solo.removeTile(solo.getList4(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b23.setVisible(false);
    }//GEN-LAST:event_b23ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(1);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(1));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b1.setVisible(false);
    }//GEN-LAST:event_b1ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed

        
        putTileOnTable(26);
        printTable();
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b14.setVisible(false);
    }//GEN-LAST:event_b14ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(27);
        printTable();
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b21.setVisible(false);
    }//GEN-LAST:event_b21ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(28);
        printTable();
        solo.removeTile(solo.getList4(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b28.setVisible(false);
    }//GEN-LAST:event_b28ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(21);
        printTable();
        remove(getIntTile(21));
        solo.removeTile(solo.getList1(), getIntTile(3));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIntTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIntTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIntTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIntTile(4));
        }
        b6.setVisible(false);
    }//GEN-LAST:event_b6ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(23);
        printTable();
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b20.setVisible(false);
    }//GEN-LAST:event_b20ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(24);
        printTable();
        solo.removeTile(solo.getList4(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b27.setVisible(false);
    }//GEN-LAST:event_b27ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(17);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(3));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b5.setVisible(false);
    }//GEN-LAST:event_b5ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(19);
        printTable();
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b19.setVisible(false);
    }//GEN-LAST:event_b19ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(20);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(1));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIntTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIntTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIntTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIntTile(4));
        }
        b26.setVisible(false);
    }//GEN-LAST:event_b26ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(13);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b4.setVisible(false);
    }//GEN-LAST:event_b4ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(14);
        printTable();
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b11.setVisible(false);
    }//GEN-LAST:event_b11ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(15);
        printTable();
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b18.setVisible(false);
    }//GEN-LAST:event_b18ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(16);
        printTable();
       solo.removeTile(solo.getList4(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b25.setVisible(false);
    }//GEN-LAST:event_b25ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(9);
        printTable();
        solo.removeTile(solo.getList1(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b3.setVisible(false);
    }//GEN-LAST:event_b3ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(10);
        printTable();
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b10.setVisible(false);
    }//GEN-LAST:event_b10ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(11);
        printTable();
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b17.setVisible(false);
    }//GEN-LAST:event_b17ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(6);
        printTable();
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b9.setVisible(false);
    }//GEN-LAST:event_b9ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
        putTileOnTable(7);
        printTable();
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
        b16.setVisible(false);
    }//GEN-LAST:event_b16ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        solo.removeTile(solo.getList2(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        solo.removeTile(solo.getList3(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        solo.removeTile(solo.getList4(), getIntTile(2));
        for (int a=0;a<28;a++){
            tileUnenable(a);
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList1()))){
            tileEnable(getIndexTile(1));
        }
        if (solo.enableTile(solo.getTheLastTile(solo.getList2()))){
            tileEnable(getIndexTile(2));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList3()))){
            tileEnable(getIndexTile(3));
        }
        if(solo.enableTile(solo.getTheLastTile(solo.getList4()))){
            tileEnable(getIndexTile(4));
        }
    }//GEN-LAST:event_b22ActionPerformed


    public void putTileOnTable(int num){
        int j = 0;
        for (Tile t : pack.getDominos()){
            j++;
            if (j == num){
                if (table.getLeftSide() == t.getSide2()){
                    table.addDominoLeft(t, false);
                }
                else if (table.getLeftSide() == t.getSide1()){
                    table.addDominoLeft(t, true);
                }
                else if (table.getRightSide() == t.getSide1()){
                    table.addDominoRight(t, false);
                }
                else{
                    table.addDominoRight(t, true);
                }
            }
        }
    }
    
    public int getIntTile(int a){
       int n = 0;
        if (a ==1){
            for (Tile t : solo.getList1()){
                n++;
            }
        }
        else if (a ==2){
            for (Tile t : solo.getList2()){
                n++;
            }
        }
        else if (a==3){
            for (Tile t : solo.getList3()){
                n++;
            }
        }
        else{
            for (Tile t : solo.getList4()){
                n++;
            }
        }
        
        return n;
    }
    
    public int getIndexTile(int a){
       int n = 0;
        if (a ==1){
            for (Tile t : solo.getList1()){
                n = solo.getList1().indexOf(t);
            }
        }
        else if (a ==2){
            for (Tile t : solo.getList2()){
                n = solo.getList2().indexOf(t);
            }
        }
        else if (a==3){
            for (Tile t : solo.getList3()){
                n = solo.getList3().indexOf(t);
            }
        }
        else{
            for (Tile t : solo.getList4()){
               n = solo.getList4().indexOf(t);
            }
        }
        
        return n;
    }
    
    public void printTable(){
        String s ="";
        if (table.isEmpty()){
            textArea2.setText("The table is Empty!");
        }
        for (Tile tile : table.getDominos()){
            s = s + tile.printHorizontal();
            textArea2.setText(s);
        }
        if (solo.getList1().isEmpty() && solo.getList2().isEmpty() && solo.getList3().isEmpty() &&solo.getList4().isEmpty()){
            jScore.setText("YOU WIN!");
        }
        else{
            if (b == 4){
                jScore.setText("YOU LOSE!");
            }
        }
    }
    
    public void createNshuffleTiles(){
        int i = 0;
        for (Tile t : pack.getDominos()){
            i++;
            switch (i) {
                case 1:
                    b1.setText(t.printHorizontal());
                    break;
                case 2:
                    b2.setText(t.printHorizontal());
                    break;
                case 3:
                    b3.setText(t.printHorizontal());
                    break;
                case 4:
                    b4.setText(t.printHorizontal());
                    break;
                case 5:
                    b5.setText(t.printHorizontal());
                    break;
                case 6:
                    b6.setText(t.printHorizontal());
                    break;
                case 7:
                    b7.setText(t.printHorizontal());
                    break;
                case 8:
                    b8.setText(t.printHorizontal());
                    break;
                case 9:
                    b9.setText(t.printHorizontal());
                    break;
                case 10:
                    b10.setText(t.printHorizontal());
                    break;
                case 11:
                    b11.setText(t.printHorizontal());
                    break;
                case 12:
                    b12.setText(t.printHorizontal());
                    break;
                case 13:
                    b13.setText(t.printHorizontal());
                    break;
                case 14:
                    b14.setText(t.printHorizontal());
                    break;
                case 15:
                    b15.setText(t.printHorizontal());
                    break;
                case 16:
                    b16.setText(t.printHorizontal());
                    break;
                case 17:
                    b17.setText(t.printHorizontal());
                    break;
                case 18:
                    b18.setText(t.printHorizontal());
                    break;
                case 19:
                    b19.setText(t.printHorizontal());
                    break;
                case 20:
                    b20.setText(t.printHorizontal());
                    break;
                case 21:
                    b21.setText(t.printHorizontal());
                    break;
                case 22:
                    b22.setText(t.printHorizontal());
                    break;
                case 23:
                    b23.setText(t.printHorizontal());
                    break;
                case 24:
                    b24.setText(t.printHorizontal());
                    break;
                case 25:
                    b25.setText(t.printHorizontal());
                    break;
                case 26:
                    b26.setText(t.printHorizontal());
                    break;
                case 27:
                    b27.setText(t.printHorizontal());
                    break;
                default:
                    b28.setText(t.printHorizontal());
                    break;
            }
        }
    }
    
     public void tileUnenable(int i){
       
            switch (i) {
                case 1:
                    b1.setEnabled(false);
                    break;
                case 2:
                    b2.setEnabled(false);
                    break;
                case 3:
                    b3.setEnabled(false);
                    break;
                case 4:
                    b4.setEnabled(false);
                    break;
                case 5:
                    b5.setEnabled(false);
                    break;
                case 6:
                    b6.setEnabled(false);
                    break;
                case 7:
                    b7.setEnabled(false);
                    break;
                case 8:
                    b8.setEnabled(false);
                    break;
                case 9:
                    b9.setEnabled(false);
                    break;
                case 10:
                    b10.setEnabled(false);
                    break;
                case 11:
                    b11.setEnabled(false);
                    break;
                case 12:
                    b12.setEnabled(false);
                    break;
                case 13:
                    b13.setEnabled(false);
                    break;
                case 14:
                    b14.setEnabled(false);
                    break;
                case 15:
                    b15.setEnabled(false);
                    break;
                case 16:
                    b16.setEnabled(false);
                    break;
                case 17:
                    b17.setEnabled(false);
                    break;
                case 18:
                    b18.setEnabled(false);
                    break;
                case 19:
                    b19.setEnabled(false);
                    break;
                case 20:
                    b20.setEnabled(false);
                    break;
                case 21:
                    b21.setEnabled(false);
                    break;
                case 22:
                    b22.setEnabled(false);
                    break;
                case 23:
                    b23.setEnabled(false);
                    break;
                case 24:
                    b24.setEnabled(false);
                    break;
                case 25:
                    b25.setEnabled(false);
                    break;
                case 26:
                    b26.setEnabled(false);
                    break;
                case 27:
                    b27.setEnabled(false);
                    break;
                default:
                    b28.setEnabled(false);
                    break;
            }
    }
    
        public void tileEnable(int i){
       
            switch (i) {
                case 1:
                    b1.setEnabled(true);
                    break;
                case 2:
                    b2.setEnabled(true);
                    break;
                case 3:
                    b3.setEnabled(true);
                    break;
                case 4:
                    b4.setEnabled(true);
                    break;
                case 5:
                    b5.setEnabled(true);
                    break;
                case 6:
                    b6.setEnabled(true);
                    break;
                case 7:
                    b7.setEnabled(true);
                    break;
                case 8:
                    b8.setEnabled(true);
                    break;
                case 9:
                    b9.setEnabled(true);
                    break;
                case 10:
                    b10.setEnabled(true);
                    break;
                case 11:
                    b11.setEnabled(true);
                    break;
                case 12:
                    b12.setEnabled(true);
                    break;
                case 13:
                    b13.setEnabled(true);
                    break;
                case 14:
                    b14.setEnabled(true);
                    break;
                case 15:
                    b15.setEnabled(true);
                    break;
                case 16:
                    b16.setEnabled(true);
                    break;
                case 17:
                    b17.setEnabled(true);
                    break;
                case 18:
                    b18.setEnabled(true);
                    break;
                case 19:
                    b19.setEnabled(true);
                    break;
                case 20:
                    b20.setEnabled(true);
                    break;
                case 21:
                    b21.setEnabled(true);
                    break;
                case 22:
                    b22.setEnabled(true);
                    break;
                case 23:
                    b23.setEnabled(true);
                    break;
                case 24:
                    b24.setEnabled(true);
                    break;
                case 25:
                    b25.setEnabled(true);
                    break;
                case 26:
                    b26.setEnabled(true);
                    break;
                case 27:
                    b27.setEnabled(true);
                    break;
                default:
                    b28.setEnabled(true);
                    break;
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solo1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solo1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solo1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solo1Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solo1Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jScore;
    private java.awt.TextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
